### ISSUE TITLE
Clarification of what is being evaluated

### ISSUE THREAD

**Issue by ogencoglu** [rentruewang/bocoel#4]
Thanks for the work!

Can you clarify in docs what is being evaluated here? Is it some low level metric like perplexity, ROUGE, BLUE etc or is it instruction-following capabilities or is it bias etc.? Or is it so that it is agnostic to the metric and one defines that alongside the dataset?

**Comment by rentruewang** [comment]
Yes, it's a (more or less) common term in LLM community to mean "benchmarking".

So the flow is typically sth like

```mermaid
graph TD;
    train --> eval;
    eval --> train;
    eval --> deploy;
```

I hope this helps!
