### ISSUE TITLE
ImportError: cannot import name 'Manager' from 'bocoel'

### ISSUE THREAD

**Issue by UBCMark** [rentruewang/bocoel#6]
I did `pip install bocoel`, but when I do `from bocoel import Manager, factories`, I got the error.

ImportError: cannot import name 'Manager' from 'bocoel' (/..../miniconda3/envs/playground/lib/python3.11/site-packages/bocoel/__init__.py)

ImportError: cannot import name 'factories' from 'bocoel' (/..../miniconda3/envs/playground/lib/python3.11/site-packages/bocoel/__init__.py)

**Comment by rentruewang** [comment]
Huh that is very very weird, as import being successful is part of the website building process. Lemme get back to you in a while.
